logo = true
logoText = "Kubernetes Reference"
logoType = "short" # long, short
description = "Kubernetes Reference"
editBaseURL = ""
themeOptions = ["light", "dark"]

useFaviconGenerator = false # https://www.favicon-generator.org/

enableTocSwitch = true
enableLandingBackground = true
enableSearch = false
enableSearchHighlight = false
enableLangChange = false
enableDarkMode = true
enableBreadcrumb = true
enableBlogBreadcrumb = true
enableEditBtn = false
enableToc = true
enableMenu = true
enableNavbar = true
enableFooter = true
showPoweredBy = true

tocLevels = ["h2", "h3", "h4"]
paginateWindow = 1
taxoPaginate = 13
taxoGroupByDate = "2006" # "2006-01": group by month, "2006": group by year

github = "https://github.com/feloy/kubernetes-resources-reference"

enableComment = false
